language: python
python:
  - 3.4
  - 3.5
  - 3.6
  - 3.7
  - 3.8
  - "3.8-dev"  # 3.8 development branch
  - "nightly"  # nightly build
# env:
#   global:
#   - secure: "<encrypted MYPYPI_USER=username>"
#   - secure: "<encrypted MYPYPI_PASS=p@ssword>"
before_install:
- pip install poetry
install:
- poetry install
script:
- poetry run task test:unit
# - poetry run coverage run --source=my_package -m unittest discover -b
# before_deploy:
# - poetry config repositories.mypypi http://mypypi.example.com/simple
# - poetry config http-basic.mypypi $MYPYPI_USER $MYPYPI_PASS
# - poetry build -f sdist
# deploy:
#   provider: script
#   script: poetry publish -r mypypi
#   skip_cleanup: true
#   on:
#     tags: true
