language: python
python:
  - 3.6
  - 3.7
  - 3.8
  - "3.8-dev"  # 3.8 development branch

os:
  - linux
  # - osx # https://travis-ci.community/t/osx-default-environment-with-python-doesnt-work/6116/2

before_install:
- pip install poetry
install:
- poetry install

script:
- poetry run task test:unit
- poetry run task test:lint
- poetry run task test:bandit

jobs:
  include:
  - stage: Coverage
    before_script:  # code coverage tool
    - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
    - chmod +x ./cc-test-reporter
    - ./cc-test-reporter before-build
    script:
    - poetry run task travis:test
    after_script:
    - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

  - stage: Publish to pypi
    deploy:
      provider: script
      script: poetry publish --username __token__ --password $PYPI_TOKEN --build
      on:
        tags: true
